# Generated by Django 4.2.6 on 2023-10-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='updates',
            new_name='updated',
        ),
    ]
